image: node:10.4.1

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm test
  branches:
    staging:
      - step:
          name: Build And Deploy
          script:
            - npm install
            - npm test
            - npm run build
            - rsync -avz dist/ $DEPLOY_TARGET
