export const LOAD_MERGED_BLOCKS = 'LOAD_MERGED_BLOCKS'
export const LOAD_STATES = 'LOAD_STATES'
export const LOAD_MORE_BLOCKS = 'LOAD_MORE_BLOCKS'
export const LOAD_BRANCHES = 'LOAD_BRANCHES'
export const LOAD_BLOCKS = 'LOAD_BLOCKS'
export const LOAD_TXS = 'LOAD_TXS'
export const LOAD_TX = 'LOAD_TX'
export const LOAD_BLOCK = 'LOAD_BLOCK'
